import Constants from 'expo-constants';

export interface R2Config {
  accountId: string;
  accessKeyId: string;
  secretAccessKey: string;
  bucketName: string;
  region: string;
  endpoint: string;
}

export const r2Config: R2Config = {
  accountId: Constants.expoConfig?.extra?.R2_ACCOUNT_ID || process.env.EXPO_PUBLIC_R2_ACCOUNT_ID || '',
  accessKeyId: Constants.expoConfig?.extra?.R2_ACCESS_KEY_ID || process.env.EXPO_PUBLIC_R2_ACCESS_KEY_ID || '',
  secretAccessKey: Constants.expoConfig?.extra?.R2_SECRET_ACCESS_KEY || process.env.EXPO_PUBLIC_R2_SECRET_ACCESS_KEY || '',
  bucketName: Constants.expoConfig?.extra?.R2_BUCKET_NAME || process.env.EXPO_PUBLIC_R2_BUCKET_NAME || '',
  region: Constants.expoConfig?.extra?.R2_REGION || process.env.EXPO_PUBLIC_R2_REGION || 'auto',
  endpoint: Constants.expoConfig?.extra?.R2_ENDPOINT || process.env.EXPO_PUBLIC_R2_ENDPOINT || '',
};

// ...removed debug log...

// Validate configuration
export const validateR2Config = (): boolean => {
  const required = ['accountId', 'accessKeyId', 'secretAccessKey', 'bucketName', 'endpoint'];
  return required.every(key => r2Config[key as keyof R2Config]);
};

// Get public URL for uploaded files (this will be replaced with signed URLs for private buckets)
export const getPublicUrl = (key: string): string => {
  // This is a placeholder URL - for private R2 buckets, we need to use signed URLs
  // The actual accessible URL will be generated by the R2 service using signed URLs
  const url = `${r2Config.endpoint}/${key}`;
  return url;
};

// Generate unique file key
export const generateFileKey = (originalName: string | undefined, prefix: string = 'media'): string => {
  const timestamp = Date.now();
  const randomId = Math.random().toString(36).substring(2, 15);
  const safeName = originalName || `file_${timestamp}`;
  const extension = safeName.split('.').pop() || '';
  return `${prefix}/${timestamp}-${randomId}.${extension}`;
};
